# Generated by Django 4.1.2 on 2026-06-23 23:54

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Reclamos'], [1, 'Sugerencias'], [2, 'Consultas'], [3, 'Problemas con mi pedido']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagenes')),
                ('editorial', models.CharField(max_length=50, verbose_name='Editotial')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombres', models.CharField(max_length=500, validators=[app.models.validar_no_vacio])),
                ('apellidos', models.CharField(max_length=500, validators=[app.models.validar_no_vacio])),
                ('telefono', models.IntegerField(validators=[app.models.validar_no_vacio])),
                ('email', models.EmailField(max_length=254, validators=[app.models.validar_no_vacio])),
            ],
        ),
    ]
