# Generated by Django 4.1.2 on 2026-06-23 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='ID de Transacción')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('total_price', models.IntegerField(verbose_name='Total Pagado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('tarjeta_ultimos_cuatro', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_titulo', models.CharField(max_length=100, verbose_name='Título del Manga')),
                ('manga_editorial', models.CharField(max_length=100, verbose_name='Editorial')),
                ('precio_unitario', models.IntegerField(verbose_name='Precio Unitario')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.manga')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.pedido')),
            ],
        ),
    ]
