# Generated by Django 4.1.2 on 2026-06-24 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Consulta'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='respondido',
            field=models.BooleanField(default=False, verbose_name='Respondido'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta del Administrador'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to=settings.AUTH_USER_MODEL),
        ),
    ]
